linha1 = lines.shift()
linha2 = lines.shift()
linha1 = linha1.split(' ')
linha2 = linha2.split(' ')
x1 = parseFloat(linha1[0])
y1 = parseFloat(linha1[1])
x2 = parseFloat(linha2[0])
y2 = parseFloat(linha2[1])
distancia = Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2)
console.log(Math.sqrt(distancia).toFixed(4))